### ISSUE TITLE
Getschools mitä palauttaa etusivun ajaxille jos ei ole kouluja

### ISSUE THREAD

**Issue by ghost** [HalooProductions/student-exchange-map#26]
Itellä tulee ainakin:   
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data   
Ja getschools.php   
Notice: Trying to get property of non-object in C:\wamp64\www\kartta-kaksi\api\getschools.php on line 11

**Comment by aspehkonen** [comment]
Korjattu
