### ISSUE TITLE
Kaupunki pois Schoolista

### ISSUE THREAD

**Issue by ghost** [HalooProductions/student-exchange-map#32]
Pois School classista,
pois admin viewistä,
testit pitää päivittää ettei lykkää koulua enää sinne,
pois etusivulta kaupunkihaku dropdown.

**Comment by ghost** [comment]
Kaupunki ei lähekkään pois kokonaan, muuttuu vain tekstikentäksi.
Ei tarvi poistaa siis requiredista, testeihin päivittää stringi numeron tilalle.

**Comment by aspehkonen** [comment]
Done
