### ISSUE TITLE
Etusivun kouluhaku

### ISSUE THREAD

**Issue by ghost** [HalooProductions/student-exchange-map#33]
Etusivun kouluhaku toimimaan -> etusivu pitää muuttaa php filuksi (tai vaihtoehtoisesti hakee javascriptillä) niin että latautuessa hakee tietokannasta kaikki koulut ja laittaa ne dropdowniin.
Koulun valitessa kohdistaa place_id:n avulla.

**Comment by aspehkonen** [comment]
Tehty javascriptillä. Markeri häviää vieläkin käytettäessä--> kts. issue #38
